name: PersianChatFixer
version: 3.1.1
main: TheFaRHaNiR.PersianChatFixer.Main
api-version: '26.2'
description: Fixes Persian text rendering in chat and signs (RTL correction)
author: TheFaRHaNiR
website: https://github.com/TheFaRHaNiR
